sudo: required
services:
    - docker

script:
    - docker build -t archlinux:dotfiles -f Dockerfile .
    - docker build -t ubuntu:dotfiles -f DockerfileUbuntu .

after_script:
    - docker run -t --rm archlinux:dotfiles dotfiles/test.sh
    - docker run -t --rm ubuntu:dotfiles    dotfiles/test.sh

