#! /bin/sh

sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-0   -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#bspc rule -a polybar state=sticky
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sleep 1

sh $HOME/.config/polybar/launch.sh
feh --randomize --bg-fill ~/Pictures/Wallpapers/*
libinput-gestures-setup start


# trayicons
! pgrep nm-applet && nm-applet
! pgrep udiskie   && udiskie -t
