#! /usr/bin/env sh
#
# wm independent hotkeys
#

# terminal emulator
super + Return
	termite
# terminal emulator with same path
super + shift + Return
	termite -d $(xcwd)
# interractive terminal emulator with same path
super + ctrl + shift + Return
	termite -d $(xcwd) -e fish

# program launcher
super + d
	zsh -c "rofi -modi drun -show drun -show-icons -icons-theme hicolor"
# program switcher
super + shift + Tab
	rofi -combi-modi window -show combi -show-icons -icons-theme hicolor
# ssh
super + e
	rofi -show ssh


# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd
# show sxhkd helper
super + shift + Escape
	cat ~/.config/sxhkd/sxhkdrc | awk -F\# '/^[a-z]/ && last \{print $0,"\t",last\} \{last=""\} /^#/\{last=$2\}' | column -t -s $'\t' | rofi -dmenu -i -no-show-icons -width 1000
	

#
# bspwm hotkeys
#

# quit/restart bspwm
super + shift + {e,r}
	bspc {quit,wm -r}

# close and kill
super + shift + {q,k}
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state (tiled,pseudo_tiled,floating,fullscreen)
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags (marked,locked,sticky,private)
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# move to next/prev monitor
super + n
	bspc monitor -f {prev,next}

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# Xbacklight controls
XF86MonBrightness{Up,Down}
	xbacklight -{inc,dec} 1
shift + XF86MonBrightness{Up,Down}
	xbacklight -{inc,dec} 5

# Pulse Audio controls
XF86Audio{RaiseVolume,LowerVolume}
	pactl set-sink-volume $(pactl info | grep "Default Sink:" | cut -d' ' -f3) {+5%,-5%}
XF86AudioMute 
	pactl set-sink-mute $(pactl info | grep "Default Sink:" | cut -d' ' -f3) toggle # mute sound

# Multimedia keys
XF86Audio{Play,Next,Prev}
	playerctl {play-pause,position 5+,position 5-}
# Multimedia keys
shift+XF86Audio{Next,Prev}
	playerctl {next,previous}

# Lockscreen
super + x 
	i3lock -c 000000 & sleep 5 && xset s activate
# Lockscreen and suspend
super + shift + x 
	i3lock -c 000000 && systemctl suspend

# Screenshot to clipboard
super + Print 
	maim -s --format=png /dev/stdout | xclip -selection clipboard -t image/png -i
# Screenshot to tmp
super + shift + Print 
	maim -s --format=png /tmp/screen$(date +'%H%M%S').png
# Screenshot helper
super + ctrl + shift + Print 
	maim -s --format=png /tmp/screen.png && /home/robi/Documents/tools/screenshot_tool/screenshot_tool.py

# Chromium
super + z
	chromium
# Chromium incognito
super + shift + z
	chromium --incognito
# Youtube Sticky
super + shift + y
	rofi -dmenu -lines 0 | xargs -I\{\} -r mpsyt /\{\},1,exit

# Change wallpaper
super + w
	feh --randomize --no-fehbg --bg-fill ~/Pictures/Wallpapers/*


# hide window
super + v
	bspc node -g hidden
# unhide window
super + shift + v
	bspc node {,$(bspc query -N -n .hidden |tail -n 1)} -g hidden=off -d $(bspc query -D -d focused --names) -t floating -f
