# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="/home/robi/.oh-my-zsh"
ZSH_THEME="../../dotfiles/zsh/bobo"
export UPDATE_ZSH_DAYS=14
COMPLETION_WAITING_DOTS="true"

plugins=(
	git
	colored-man-pages 
	extract
	sudo
	python
	pip
	vagrant
	docker
)

# User configuration

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd notify
bindkey -v
# End of lines configured by zsh-newuser-install


# The following lines were added by compinstall
zstyle :compinstall filename '/home/robi/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export KEYTIMEOUT=1

source $HOME/dotfiles/zsh/aliases

## source OhMyZsh
source $ZSH/oh-my-zsh.sh

#vars
export TERM=xterm-256color
export VISUAL="vim"
export GOPATH=/home/robi/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/home/$USER/.bin 
export PATH=$PATH:/home/$USER/.local/bin 
export PATH=$PATH:/home/$USER/scripts
